disabled_rules:
  - line_length
  - notification_center_detachment
  - void_return
  - function_body_length
  - identifier_name
  - file_length
  - function_parameter_count
  - private_over_fileprivate
  - type_body_length
  - type_name
  - large_tuple
  - empty_parentheses_with_trailing_closure
  - trailing_comma
  - for_where
  - cyclomatic_complexity
  - todo
  - control_statement
  - block_based_kvo
  - comment_spacing
  - nesting
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
vertical_whitespace:
  severity: error
included:
  - delighted/Classes/
excluded:
  - _Pods.xcodeproj
  - Example
